export const locations = [
  "Oreburgh Mine B1F",
  "Oreburgh Mine B2F",
  "Valley Windworks",
  "Eterna Forest",
  "Fuego Ironworks",
  "Mt. Coronet 1F 1",
  "Mt. Coronet 2F",
  "Mt. Coronet 3F",
  "Mt. Coronet Summit",
  "Mt. Coronet 4F 1-2",
  "Mt. Coronet 4F 3",
  "Mt. Coronet 5F",
  "Mt. Coronet 6F",
  "Mt. Coronet 1F 2",
  "Mt. Coronet Upper 1F 2",
  "Mt. Coronet Upper 1F 1",
  "Mt. Coronet Upper B1F",
  "Solaceon Ruins 2F",
  "Solaceon Ruins",
  "Solaceon Ruins B1F (4 Stairs)",
  "Solaceon Ruins B2F (4 Stairs)",
  "Solaceon Ruins B3F (3 Stairs)",
  "Solaceon Ruins B3F (4 Stairs)",
  "Solaceon Ruins B4F (4 Stairs)",
  "Solaceon Ruins B4F (Chamber)",
  "Victory Road 1F",
  "Victory Road 2F",
  "Victory Road B1F",
  "Victory Road 1F Back 2",
  "Victory Road 1F Back 1",
  "Victory Road 1F Back 3",
  "Ravaged Path",
  "Oreburgh Gate 1F",
  "Oreburgh Gate B1F",
  "Stark Mountain",
  "Stark Mountain Interior 1",
  "Stark Mountain Interior 2",
  "Sendoff Spring",
  "Turnback Cave Entrance",
  "Snowpoint Temple 1F",
  "Snowpoint Temple B1F",
  "Snowpoint Temple B2F",
  "Snowpoint Temple B3F",
  "Snowpoint Temple B4F",
  "Snowpoint Temple B5F",
  "Wayward Cave 1F",
  "Wayward Cave B1F",
  "Ruin Maniac Cave (< 10 Unown)",
  "Trophy Garden",
  "Iron Island 1F",
  "Iron Island B1F 1",
  "Iron Island B1F 2",
  "Iron Island B2F 1",
  "Iron Island B2F 2",
  "Iron Island B3F 1",
  "Old Chateau",
  "Old Chateau 2F (Eye Room)",
  "Lake Verity (Pre Team Galactic Event)",
  "Lake Verity (Post Team Galactic Event)",
  "Lake Valor",
  "Lake Acuity",
  "Valor Lakefront",
  "Acuity Lakefront",
  "Route 201",
  "Route 202",
  "Route 203",
  "Route 204 (South)",
  "Route 204 (North)",
  "Route 205 (South)",
  "Route 205 (North)",
  "Route 206",
  "Route 207",
  "Route 208",
  "Route 209",
  "Lost Tower 1F",
  "Lost Tower 2F",
  "Lost Tower 3F",
  "Lost Tower 4F",
  "Lost Tower 5F",
  "Route 210 (South)",
  "Route 210 (North)",
  "Route 211 (West)",
  "Route 211 (East)",
  "Route 212 (North)",
  "Route 212 (South)",
  "Route 213",
  "Route 214",
  "Route 215",
  "Route 216",
  "Route 217",
  "Route 218",
  "Route 221",
  "Route 222",
  "Route 224",
  "Route 225",
  "Route 227",
  "Route 228",
  "Route 229",
  "Route 226",
  "Route 230",
  "Great Marsh Area 1",
  "Great Marsh Area 2",
  "Great Marsh Area 3",
  "Great Marsh Area 4",
  "Great Marsh Area 5",
  "Great Marsh Area 6",
  "Ruin Maniac Cave (> 10 Unown)",
  "Maniac Tunnel",
  "Turnback 1st Pillar",
  "Turnback 2nd Pillar",
] as const;

export type Location = (typeof locations)[number];
